name: FrozedHider
version: ${project.version}
main: club.frozed.hider.FrozedHider
api-version: 1.20
authors: [ Elb1to ]
description: WorldGuard flag plugin for hiding players in regions
website: www.frozed.club
depend: [ WorldGuard ]
permissions:
  frozedhider.see-always:
    description: "Players with this permission are always visible (never hidden by the plugin)."
    default: op
  frozedhider.toggle:
    description: "Allows toggling the viewing of hidden players with /togglehider."
    default: op